CREATE TABLE MEMBER (
    MEMBER_NO VARCHAR2(20) NOT NULL,
    MEMBER_PW VARCHAR2(50) NULL,
    MEMBER_ADDR VARCHAR2(150) NULL,
    MEMBER_EMAIL VARCHAR2(50) NULL,
    MEMBER_PHONE CHAR(11) NULL,
    MEMBER_GEN CHAR(1) NULL,
    MEMBER_DATE DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_GRADE NUMBER NULL,
    MEMBER_TERM NUMBER NULL,
    MEMBER_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    DEPARTMENT_NO NUMBER NOT NULL,
    MEMBER_BIRTH DATE NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_NO NUMBER NOT NULL,
    DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
    DEPARTMENT_PRICE NUMBER DEFAULT 100 NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_NO)
);

-- MEMBER 테이블에 샘플 데이터 삽입
INSERT INTO MEMBER (MEMBER_NO, MEMBER_PW, MEMBER_ADDR, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_GEN, MEMBER_NAME, DEPARTMENT_NO, MEMBER_BIRTH)
VALUES ('01-1234567', 'password1', '1234 Street, City', 'member1@example.com', '12345678901', 'M', 'John Doe', 1, TO_DATE('1990-01-01', 'YYYY-MM-DD'));

INSERT INTO MEMBER (MEMBER_NO, MEMBER_PW, MEMBER_ADDR, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_GEN, MEMBER_NAME, DEPARTMENT_NO, MEMBER_BIRTH)
VALUES ('01-2345678', 'password2', '5678 Avenue, Town', 'member2@example.com', '23456789012', 'F', 'Jane Smith', 2, TO_DATE('1991-02-02', 'YYYY-MM-DD'));

INSERT INTO MEMBER (MEMBER_NO, MEMBER_PW, MEMBER_ADDR, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_GEN, MEMBER_NAME, DEPARTMENT_NO, MEMBER_BIRTH)
VALUES ('01-3456789', 'password3', '91011 Road, Village', 'member3@example.com', '34567890123', 'M', 'Michael Johnson', 3, TO_DATE('1992-03-03', 'YYYY-MM-DD'));

INSERT INTO MEMBER (MEMBER_NO, MEMBER_PW, MEMBER_ADDR, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_GEN, MEMBER_NAME, DEPARTMENT_NO, MEMBER_BIRTH)
VALUES ('01-4567890', 'password4', '121314 Lane, County', 'member4@example.com', '45678901234', 'F', 'Emily Williams', 1, TO_DATE('1993-04-04', 'YYYY-MM-DD'));

INSERT INTO MEMBER (MEMBER_NO, MEMBER_PW, MEMBER_ADDR, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_GEN, MEMBER_NAME, DEPARTMENT_NO, MEMBER_BIRTH)
VALUES ('01-5678901', 'password5', '151617 Drive, District', 'member5@example.com', '56789012345', 'M', 'Christopher Brown', 2, TO_DATE('1994-05-05', 'YYYY-MM-DD'));

-- DEPARTMENT 테이블에 샘플 데이터 삽입
INSERT INTO DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, DEPARTMENT_PRICE)
VALUES (1, 'Computer Science', 150);

INSERT INTO DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, DEPARTMENT_PRICE)
VALUES (2, 'Mathematics', 120);

INSERT INTO DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, DEPARTMENT_PRICE)
VALUES (3, 'Physics', 130);

INSERT INTO DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, DEPARTMENT_PRICE)
VALUES (4, 'Biology', 110);

INSERT INTO DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, DEPARTMENT_PRICE)
VALUES (5, 'Chemistry', 140);

COMMIT;

